# Generated by Django 4.1.5 on 2023-01-26 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personelCardNo', models.IntegerField(max_length=5)),
                ('time', models.DateTimeField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='PersonelList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personelCardNo', models.IntegerField(max_length=5)),
                ('personelName', models.CharField(max_length=200)),
            ],
        ),
    ]
