# Generated by Django 4.1.5 on 2023-01-26 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uploadlog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inout',
            name='personel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='uploadlog.personellist'),
        ),
    ]
