# Generated by Django 4.1.5 on 2023-01-27 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadlog', '0004_alter_inout_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inout',
            name='personel',
        ),
        migrations.AddField(
            model_name='inout',
            name='personelCardNo',
            field=models.IntegerField(default=0, max_length=5),
            preserve_default=False,
        ),
    ]
