# Generated by Django 4.1.5 on 2023-01-27 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadlog', '0006_alter_inout_personelcardno'),
    ]

    operations = [
        migrations.AddField(
            model_name='inout',
            name='girisCikis',
            field=models.CharField(default='', max_length=5),
        ),
    ]
