# Generated by Django 4.1.5 on 2023-01-27 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadlog', '0007_inout_giriscikis'),
    ]

    operations = [
        migrations.AddField(
            model_name='inout',
            name='personelName',
            field=models.CharField(default='', max_length=250),
        ),
    ]
