# Generated by Django 4.1.5 on 2023-02-01 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadlog', '0008_inout_personelname'),
    ]

    operations = [
        migrations.AddField(
            model_name='inout',
            name='notlar',
            field=models.CharField(default='', max_length=250, verbose_name='Not'),
        ),
        migrations.AlterField(
            model_name='inout',
            name='date',
            field=models.DateField(verbose_name='Tarih'),
        ),
        migrations.AlterField(
            model_name='inout',
            name='girisCikis',
            field=models.CharField(default='', max_length=5, verbose_name='Durum'),
        ),
        migrations.AlterField(
            model_name='inout',
            name='personelCardNo',
            field=models.IntegerField(default=0, verbose_name='Kart No'),
        ),
        migrations.AlterField(
            model_name='inout',
            name='personelName',
            field=models.CharField(default='', max_length=250, verbose_name='Ad Soyad'),
        ),
        migrations.AlterField(
            model_name='inout',
            name='time',
            field=models.TimeField(verbose_name='Saat'),
        ),
        migrations.AlterField(
            model_name='personellist',
            name='personelCardNo',
            field=models.IntegerField(verbose_name='Kart No'),
        ),
        migrations.AlterField(
            model_name='personellist',
            name='personelName',
            field=models.CharField(max_length=200, verbose_name='Ad Soyad'),
        ),
    ]
