# Generated by Django 4.1.5 on 2023-02-01 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadlog', '0009_inout_notlar_alter_inout_date_alter_inout_giriscikis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inout',
            name='girisCikis',
            field=models.CharField(default='', max_length=25, verbose_name='Durum'),
        ),
    ]
