# Generated by Django 4.1.5 on 2023-02-01 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadlog', '0010_alter_inout_giriscikis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inout',
            name='notlar',
            field=models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='Not'),
        ),
    ]
